export {
  getPopularMovies,
  getUpcomingMovies,
  getPopularTv,
  getTopRatedTv,
  getAiringTv,
  getMovieDetail,
  getTvDetail,
  getMovieVideo,
  getTvVideo,
  getSearchMovies,
  getSearchTvs,
  getDiscover,
  IMAGE_URI,
} from "./TmdbApi";
